namespace Restuarant_POS
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.label1 = new System.Windows.Forms.Label();
            this.panel2 = new System.Windows.Forms.Panel();
            this.panel3 = new System.Windows.Forms.Panel();
            this.panel4 = new System.Windows.Forms.Panel();
            this.panel6 = new System.Windows.Forms.Panel();
            this.panel7 = new System.Windows.Forms.Panel();
            this.pnData = new System.Windows.Forms.Panel();
            this.btnDessert = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnHot = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCool = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAlcohol = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnFood = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAllItem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDashboard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnMinimize = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.panel3.SuspendLayout();
            this.panel4.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.panel1.Controls.Add(this.label1);
            this.panel1.Controls.Add(this.btnMinimize);
            this.panel1.Controls.Add(this.btnClose);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(10, 10);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1802, 40);
            this.panel1.TabIndex = 0;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Kode Mono", 21.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(729, -1);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(275, 45);
            this.label1.TabIndex = 1;
            this.label1.Text = "RESTUATRANT POS";
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.btnDessert);
            this.panel2.Controls.Add(this.btnHot);
            this.panel2.Controls.Add(this.btnCool);
            this.panel2.Controls.Add(this.btnAlcohol);
            this.panel2.Controls.Add(this.btnFood);
            this.panel2.Controls.Add(this.btnAllItem);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel2.Location = new System.Drawing.Point(0, 119);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(200, 700);
            this.panel2.TabIndex = 1;
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.panel2);
            this.panel3.Controls.Add(this.panel4);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel3.Location = new System.Drawing.Point(10, 50);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(200, 819);
            this.panel3.TabIndex = 1;
            // 
            // panel4
            // 
            this.panel4.Controls.Add(this.btnDashboard);
            this.panel4.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel4.Location = new System.Drawing.Point(0, 0);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(200, 119);
            this.panel4.TabIndex = 1;
            // 
            // panel6
            // 
            this.panel6.BackColor = System.Drawing.Color.Transparent;
            this.panel6.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel6.Location = new System.Drawing.Point(220, 50);
            this.panel6.Margin = new System.Windows.Forms.Padding(10, 10, 3, 3);
            this.panel6.Name = "panel6";
            this.panel6.Size = new System.Drawing.Size(1592, 10);
            this.panel6.TabIndex = 2;
            // 
            // panel7
            // 
            this.panel7.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.panel7.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel7.Location = new System.Drawing.Point(210, 50);
            this.panel7.Margin = new System.Windows.Forms.Padding(10, 10, 3, 3);
            this.panel7.Name = "panel7";
            this.panel7.Size = new System.Drawing.Size(10, 819);
            this.panel7.TabIndex = 2;
            // 
            // pnData
            // 
            this.pnData.BackColor = System.Drawing.SystemColors.AppWorkspace;
            this.pnData.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnData.Location = new System.Drawing.Point(210, 50);
            this.pnData.Name = "pnData";
            this.pnData.Size = new System.Drawing.Size(1602, 819);
            this.pnData.TabIndex = 3;
            // 
            // btnDessert
            // 
            this.btnDessert.AllowAnimations = true;
            this.btnDessert.AllowMouseEffects = true;
            this.btnDessert.AllowToggling = false;
            this.btnDessert.AnimationSpeed = 200;
            this.btnDessert.AutoGenerateColors = false;
            this.btnDessert.AutoRoundBorders = false;
            this.btnDessert.AutoSizeLeftIcon = true;
            this.btnDessert.AutoSizeRightIcon = true;
            this.btnDessert.BackColor = System.Drawing.Color.Transparent;
            this.btnDessert.BackColor1 = System.Drawing.Color.Transparent;
            this.btnDessert.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDessert.BackgroundImage")));
            this.btnDessert.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDessert.ButtonText = "DESSERTS";
            this.btnDessert.ButtonTextMarginLeft = 0;
            this.btnDessert.ColorContrastOnClick = 45;
            this.btnDessert.ColorContrastOnHover = 45;
            this.btnDessert.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges19.BottomLeft = true;
            borderEdges19.BottomRight = true;
            borderEdges19.TopLeft = true;
            borderEdges19.TopRight = true;
            this.btnDessert.CustomizableEdges = borderEdges19;
            this.btnDessert.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDessert.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDessert.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDessert.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDessert.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnDessert.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDessert.Font = new System.Drawing.Font("Kode Mono", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDessert.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnDessert.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDessert.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDessert.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDessert.IconMarginLeft = 11;
            this.btnDessert.IconPadding = 10;
            this.btnDessert.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDessert.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDessert.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDessert.IconSize = 25;
            this.btnDessert.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnDessert.IdleBorderRadius = 1;
            this.btnDessert.IdleBorderThickness = 1;
            this.btnDessert.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnDessert.IdleIconLeftImage = global::Restuarant_POS.Properties.Resources.party_regular_241;
            this.btnDessert.IdleIconRightImage = null;
            this.btnDessert.IndicateFocus = false;
            this.btnDessert.Location = new System.Drawing.Point(0, 230);
            this.btnDessert.Name = "btnDessert";
            this.btnDessert.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDessert.OnDisabledState.BorderRadius = 1;
            this.btnDessert.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDessert.OnDisabledState.BorderThickness = 1;
            this.btnDessert.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDessert.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDessert.OnDisabledState.IconLeftImage = null;
            this.btnDessert.OnDisabledState.IconRightImage = null;
            this.btnDessert.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDessert.onHoverState.BorderRadius = 1;
            this.btnDessert.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDessert.onHoverState.BorderThickness = 1;
            this.btnDessert.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDessert.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDessert.onHoverState.IconLeftImage = null;
            this.btnDessert.onHoverState.IconRightImage = null;
            this.btnDessert.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnDessert.OnIdleState.BorderRadius = 1;
            this.btnDessert.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDessert.OnIdleState.BorderThickness = 1;
            this.btnDessert.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnDessert.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnDessert.OnIdleState.IconLeftImage = global::Restuarant_POS.Properties.Resources.party_regular_241;
            this.btnDessert.OnIdleState.IconRightImage = null;
            this.btnDessert.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDessert.OnPressedState.BorderRadius = 1;
            this.btnDessert.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDessert.OnPressedState.BorderThickness = 1;
            this.btnDessert.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDessert.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDessert.OnPressedState.IconLeftImage = null;
            this.btnDessert.OnPressedState.IconRightImage = null;
            this.btnDessert.Size = new System.Drawing.Size(200, 46);
            this.btnDessert.TabIndex = 0;
            this.btnDessert.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDessert.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDessert.TextMarginLeft = 0;
            this.btnDessert.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDessert.UseDefaultRadiusAndThickness = true;
            // 
            // btnHot
            // 
            this.btnHot.AllowAnimations = true;
            this.btnHot.AllowMouseEffects = true;
            this.btnHot.AllowToggling = false;
            this.btnHot.AnimationSpeed = 200;
            this.btnHot.AutoGenerateColors = false;
            this.btnHot.AutoRoundBorders = false;
            this.btnHot.AutoSizeLeftIcon = true;
            this.btnHot.AutoSizeRightIcon = true;
            this.btnHot.BackColor = System.Drawing.Color.Transparent;
            this.btnHot.BackColor1 = System.Drawing.Color.Transparent;
            this.btnHot.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHot.BackgroundImage")));
            this.btnHot.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHot.ButtonText = "HOT DRINK";
            this.btnHot.ButtonTextMarginLeft = 0;
            this.btnHot.ColorContrastOnClick = 45;
            this.btnHot.ColorContrastOnHover = 45;
            this.btnHot.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges20.BottomLeft = true;
            borderEdges20.BottomRight = true;
            borderEdges20.TopLeft = true;
            borderEdges20.TopRight = true;
            this.btnHot.CustomizableEdges = borderEdges20;
            this.btnHot.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHot.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHot.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHot.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHot.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnHot.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHot.Font = new System.Drawing.Font("Kode Mono", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnHot.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHot.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnHot.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHot.IconMarginLeft = 11;
            this.btnHot.IconPadding = 10;
            this.btnHot.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHot.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnHot.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHot.IconSize = 25;
            this.btnHot.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnHot.IdleBorderRadius = 1;
            this.btnHot.IdleBorderThickness = 1;
            this.btnHot.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnHot.IdleIconLeftImage = global::Restuarant_POS.Properties.Resources.hot_solid_241;
            this.btnHot.IdleIconRightImage = null;
            this.btnHot.IndicateFocus = false;
            this.btnHot.Location = new System.Drawing.Point(0, 184);
            this.btnHot.Name = "btnHot";
            this.btnHot.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHot.OnDisabledState.BorderRadius = 1;
            this.btnHot.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHot.OnDisabledState.BorderThickness = 1;
            this.btnHot.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHot.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHot.OnDisabledState.IconLeftImage = null;
            this.btnHot.OnDisabledState.IconRightImage = null;
            this.btnHot.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnHot.onHoverState.BorderRadius = 1;
            this.btnHot.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHot.onHoverState.BorderThickness = 1;
            this.btnHot.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnHot.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnHot.onHoverState.IconLeftImage = null;
            this.btnHot.onHoverState.IconRightImage = null;
            this.btnHot.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnHot.OnIdleState.BorderRadius = 1;
            this.btnHot.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHot.OnIdleState.BorderThickness = 1;
            this.btnHot.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnHot.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnHot.OnIdleState.IconLeftImage = global::Restuarant_POS.Properties.Resources.hot_solid_241;
            this.btnHot.OnIdleState.IconRightImage = null;
            this.btnHot.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHot.OnPressedState.BorderRadius = 1;
            this.btnHot.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHot.OnPressedState.BorderThickness = 1;
            this.btnHot.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHot.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHot.OnPressedState.IconLeftImage = null;
            this.btnHot.OnPressedState.IconRightImage = null;
            this.btnHot.Size = new System.Drawing.Size(200, 46);
            this.btnHot.TabIndex = 0;
            this.btnHot.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHot.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHot.TextMarginLeft = 0;
            this.btnHot.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHot.UseDefaultRadiusAndThickness = true;
            // 
            // btnCool
            // 
            this.btnCool.AllowAnimations = true;
            this.btnCool.AllowMouseEffects = true;
            this.btnCool.AllowToggling = false;
            this.btnCool.AnimationSpeed = 200;
            this.btnCool.AutoGenerateColors = false;
            this.btnCool.AutoRoundBorders = false;
            this.btnCool.AutoSizeLeftIcon = true;
            this.btnCool.AutoSizeRightIcon = true;
            this.btnCool.BackColor = System.Drawing.Color.Transparent;
            this.btnCool.BackColor1 = System.Drawing.Color.Transparent;
            this.btnCool.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCool.BackgroundImage")));
            this.btnCool.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCool.ButtonText = "COOL DRINK";
            this.btnCool.ButtonTextMarginLeft = 0;
            this.btnCool.ColorContrastOnClick = 45;
            this.btnCool.ColorContrastOnHover = 45;
            this.btnCool.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges21.BottomLeft = true;
            borderEdges21.BottomRight = true;
            borderEdges21.TopLeft = true;
            borderEdges21.TopRight = true;
            this.btnCool.CustomizableEdges = borderEdges21;
            this.btnCool.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCool.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCool.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCool.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCool.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCool.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCool.Font = new System.Drawing.Font("Kode Mono", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCool.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnCool.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCool.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCool.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCool.IconMarginLeft = 11;
            this.btnCool.IconPadding = 10;
            this.btnCool.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCool.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCool.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCool.IconSize = 25;
            this.btnCool.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnCool.IdleBorderRadius = 1;
            this.btnCool.IdleBorderThickness = 1;
            this.btnCool.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnCool.IdleIconLeftImage = global::Restuarant_POS.Properties.Resources.drink_solid_241;
            this.btnCool.IdleIconRightImage = null;
            this.btnCool.IndicateFocus = false;
            this.btnCool.Location = new System.Drawing.Point(0, 138);
            this.btnCool.Name = "btnCool";
            this.btnCool.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCool.OnDisabledState.BorderRadius = 1;
            this.btnCool.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCool.OnDisabledState.BorderThickness = 1;
            this.btnCool.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCool.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCool.OnDisabledState.IconLeftImage = null;
            this.btnCool.OnDisabledState.IconRightImage = null;
            this.btnCool.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCool.onHoverState.BorderRadius = 1;
            this.btnCool.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCool.onHoverState.BorderThickness = 1;
            this.btnCool.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCool.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCool.onHoverState.IconLeftImage = null;
            this.btnCool.onHoverState.IconRightImage = null;
            this.btnCool.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCool.OnIdleState.BorderRadius = 1;
            this.btnCool.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCool.OnIdleState.BorderThickness = 1;
            this.btnCool.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnCool.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnCool.OnIdleState.IconLeftImage = global::Restuarant_POS.Properties.Resources.drink_solid_241;
            this.btnCool.OnIdleState.IconRightImage = null;
            this.btnCool.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCool.OnPressedState.BorderRadius = 1;
            this.btnCool.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCool.OnPressedState.BorderThickness = 1;
            this.btnCool.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCool.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCool.OnPressedState.IconLeftImage = null;
            this.btnCool.OnPressedState.IconRightImage = null;
            this.btnCool.Size = new System.Drawing.Size(200, 46);
            this.btnCool.TabIndex = 0;
            this.btnCool.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCool.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCool.TextMarginLeft = 0;
            this.btnCool.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCool.UseDefaultRadiusAndThickness = true;
            // 
            // btnAlcohol
            // 
            this.btnAlcohol.AllowAnimations = true;
            this.btnAlcohol.AllowMouseEffects = true;
            this.btnAlcohol.AllowToggling = false;
            this.btnAlcohol.AnimationSpeed = 200;
            this.btnAlcohol.AutoGenerateColors = false;
            this.btnAlcohol.AutoRoundBorders = false;
            this.btnAlcohol.AutoSizeLeftIcon = true;
            this.btnAlcohol.AutoSizeRightIcon = true;
            this.btnAlcohol.BackColor = System.Drawing.Color.Transparent;
            this.btnAlcohol.BackColor1 = System.Drawing.Color.Transparent;
            this.btnAlcohol.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAlcohol.BackgroundImage")));
            this.btnAlcohol.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAlcohol.ButtonText = "ALCOHOL";
            this.btnAlcohol.ButtonTextMarginLeft = 0;
            this.btnAlcohol.ColorContrastOnClick = 45;
            this.btnAlcohol.ColorContrastOnHover = 45;
            this.btnAlcohol.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges22.BottomLeft = true;
            borderEdges22.BottomRight = true;
            borderEdges22.TopLeft = true;
            borderEdges22.TopRight = true;
            this.btnAlcohol.CustomizableEdges = borderEdges22;
            this.btnAlcohol.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAlcohol.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAlcohol.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAlcohol.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAlcohol.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnAlcohol.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAlcohol.Font = new System.Drawing.Font("Kode Mono", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAlcohol.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnAlcohol.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAlcohol.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAlcohol.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAlcohol.IconMarginLeft = 11;
            this.btnAlcohol.IconPadding = 10;
            this.btnAlcohol.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAlcohol.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAlcohol.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAlcohol.IconSize = 25;
            this.btnAlcohol.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnAlcohol.IdleBorderRadius = 1;
            this.btnAlcohol.IdleBorderThickness = 1;
            this.btnAlcohol.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnAlcohol.IdleIconLeftImage = global::Restuarant_POS.Properties.Resources.beer_regular_241;
            this.btnAlcohol.IdleIconRightImage = null;
            this.btnAlcohol.IndicateFocus = false;
            this.btnAlcohol.Location = new System.Drawing.Point(0, 92);
            this.btnAlcohol.Name = "btnAlcohol";
            this.btnAlcohol.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAlcohol.OnDisabledState.BorderRadius = 1;
            this.btnAlcohol.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAlcohol.OnDisabledState.BorderThickness = 1;
            this.btnAlcohol.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAlcohol.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAlcohol.OnDisabledState.IconLeftImage = null;
            this.btnAlcohol.OnDisabledState.IconRightImage = null;
            this.btnAlcohol.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAlcohol.onHoverState.BorderRadius = 1;
            this.btnAlcohol.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAlcohol.onHoverState.BorderThickness = 1;
            this.btnAlcohol.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAlcohol.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAlcohol.onHoverState.IconLeftImage = null;
            this.btnAlcohol.onHoverState.IconRightImage = null;
            this.btnAlcohol.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnAlcohol.OnIdleState.BorderRadius = 1;
            this.btnAlcohol.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAlcohol.OnIdleState.BorderThickness = 1;
            this.btnAlcohol.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnAlcohol.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnAlcohol.OnIdleState.IconLeftImage = global::Restuarant_POS.Properties.Resources.beer_regular_241;
            this.btnAlcohol.OnIdleState.IconRightImage = null;
            this.btnAlcohol.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAlcohol.OnPressedState.BorderRadius = 1;
            this.btnAlcohol.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAlcohol.OnPressedState.BorderThickness = 1;
            this.btnAlcohol.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAlcohol.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAlcohol.OnPressedState.IconLeftImage = null;
            this.btnAlcohol.OnPressedState.IconRightImage = null;
            this.btnAlcohol.Size = new System.Drawing.Size(200, 46);
            this.btnAlcohol.TabIndex = 0;
            this.btnAlcohol.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAlcohol.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAlcohol.TextMarginLeft = 0;
            this.btnAlcohol.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAlcohol.UseDefaultRadiusAndThickness = true;
            // 
            // btnFood
            // 
            this.btnFood.AllowAnimations = true;
            this.btnFood.AllowMouseEffects = true;
            this.btnFood.AllowToggling = false;
            this.btnFood.AnimationSpeed = 200;
            this.btnFood.AutoGenerateColors = false;
            this.btnFood.AutoRoundBorders = false;
            this.btnFood.AutoSizeLeftIcon = true;
            this.btnFood.AutoSizeRightIcon = true;
            this.btnFood.BackColor = System.Drawing.Color.Transparent;
            this.btnFood.BackColor1 = System.Drawing.Color.Transparent;
            this.btnFood.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFood.BackgroundImage")));
            this.btnFood.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFood.ButtonText = "FOOD";
            this.btnFood.ButtonTextMarginLeft = 0;
            this.btnFood.ColorContrastOnClick = 45;
            this.btnFood.ColorContrastOnHover = 45;
            this.btnFood.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges23.BottomLeft = true;
            borderEdges23.BottomRight = true;
            borderEdges23.TopLeft = true;
            borderEdges23.TopRight = true;
            this.btnFood.CustomizableEdges = borderEdges23;
            this.btnFood.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFood.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFood.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFood.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFood.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnFood.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFood.Font = new System.Drawing.Font("Kode Mono", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFood.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnFood.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFood.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFood.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFood.IconMarginLeft = 11;
            this.btnFood.IconPadding = 10;
            this.btnFood.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFood.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFood.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFood.IconSize = 25;
            this.btnFood.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnFood.IdleBorderRadius = 1;
            this.btnFood.IdleBorderThickness = 1;
            this.btnFood.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnFood.IdleIconLeftImage = global::Restuarant_POS.Properties.Resources.bowl_hot_regular_241;
            this.btnFood.IdleIconRightImage = null;
            this.btnFood.IndicateFocus = false;
            this.btnFood.Location = new System.Drawing.Point(0, 46);
            this.btnFood.Name = "btnFood";
            this.btnFood.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFood.OnDisabledState.BorderRadius = 1;
            this.btnFood.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFood.OnDisabledState.BorderThickness = 1;
            this.btnFood.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFood.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFood.OnDisabledState.IconLeftImage = null;
            this.btnFood.OnDisabledState.IconRightImage = null;
            this.btnFood.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFood.onHoverState.BorderRadius = 1;
            this.btnFood.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFood.onHoverState.BorderThickness = 1;
            this.btnFood.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFood.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnFood.onHoverState.IconLeftImage = null;
            this.btnFood.onHoverState.IconRightImage = null;
            this.btnFood.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnFood.OnIdleState.BorderRadius = 1;
            this.btnFood.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFood.OnIdleState.BorderThickness = 1;
            this.btnFood.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnFood.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnFood.OnIdleState.IconLeftImage = global::Restuarant_POS.Properties.Resources.bowl_hot_regular_241;
            this.btnFood.OnIdleState.IconRightImage = null;
            this.btnFood.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFood.OnPressedState.BorderRadius = 1;
            this.btnFood.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFood.OnPressedState.BorderThickness = 1;
            this.btnFood.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFood.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFood.OnPressedState.IconLeftImage = null;
            this.btnFood.OnPressedState.IconRightImage = null;
            this.btnFood.Size = new System.Drawing.Size(200, 46);
            this.btnFood.TabIndex = 0;
            this.btnFood.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFood.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFood.TextMarginLeft = 0;
            this.btnFood.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnFood.UseDefaultRadiusAndThickness = true;
            this.btnFood.Click += new System.EventHandler(this.btnFood_Click);
            // 
            // btnAllItem
            // 
            this.btnAllItem.AllowAnimations = true;
            this.btnAllItem.AllowMouseEffects = true;
            this.btnAllItem.AllowToggling = false;
            this.btnAllItem.AnimationSpeed = 200;
            this.btnAllItem.AutoGenerateColors = false;
            this.btnAllItem.AutoRoundBorders = false;
            this.btnAllItem.AutoSizeLeftIcon = true;
            this.btnAllItem.AutoSizeRightIcon = true;
            this.btnAllItem.BackColor = System.Drawing.Color.Transparent;
            this.btnAllItem.BackColor1 = System.Drawing.Color.Transparent;
            this.btnAllItem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAllItem.BackgroundImage")));
            this.btnAllItem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllItem.ButtonText = "ALL ITEMS";
            this.btnAllItem.ButtonTextMarginLeft = 0;
            this.btnAllItem.ColorContrastOnClick = 45;
            this.btnAllItem.ColorContrastOnHover = 45;
            this.btnAllItem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges24.BottomLeft = true;
            borderEdges24.BottomRight = true;
            borderEdges24.TopLeft = true;
            borderEdges24.TopRight = true;
            this.btnAllItem.CustomizableEdges = borderEdges24;
            this.btnAllItem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAllItem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAllItem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAllItem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAllItem.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnAllItem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAllItem.Font = new System.Drawing.Font("Kode Mono", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAllItem.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnAllItem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAllItem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAllItem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAllItem.IconMarginLeft = 11;
            this.btnAllItem.IconPadding = 10;
            this.btnAllItem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAllItem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAllItem.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAllItem.IconSize = 25;
            this.btnAllItem.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnAllItem.IdleBorderRadius = 1;
            this.btnAllItem.IdleBorderThickness = 1;
            this.btnAllItem.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnAllItem.IdleIconLeftImage = global::Restuarant_POS.Properties.Resources.infinite_regular_24;
            this.btnAllItem.IdleIconRightImage = null;
            this.btnAllItem.IndicateFocus = false;
            this.btnAllItem.Location = new System.Drawing.Point(0, 0);
            this.btnAllItem.Name = "btnAllItem";
            this.btnAllItem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAllItem.OnDisabledState.BorderRadius = 1;
            this.btnAllItem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllItem.OnDisabledState.BorderThickness = 1;
            this.btnAllItem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAllItem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAllItem.OnDisabledState.IconLeftImage = null;
            this.btnAllItem.OnDisabledState.IconRightImage = null;
            this.btnAllItem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAllItem.onHoverState.BorderRadius = 1;
            this.btnAllItem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllItem.onHoverState.BorderThickness = 1;
            this.btnAllItem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAllItem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAllItem.onHoverState.IconLeftImage = null;
            this.btnAllItem.onHoverState.IconRightImage = null;
            this.btnAllItem.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnAllItem.OnIdleState.BorderRadius = 1;
            this.btnAllItem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllItem.OnIdleState.BorderThickness = 1;
            this.btnAllItem.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnAllItem.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnAllItem.OnIdleState.IconLeftImage = global::Restuarant_POS.Properties.Resources.infinite_regular_24;
            this.btnAllItem.OnIdleState.IconRightImage = null;
            this.btnAllItem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAllItem.OnPressedState.BorderRadius = 1;
            this.btnAllItem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllItem.OnPressedState.BorderThickness = 1;
            this.btnAllItem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAllItem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAllItem.OnPressedState.IconLeftImage = null;
            this.btnAllItem.OnPressedState.IconRightImage = null;
            this.btnAllItem.Size = new System.Drawing.Size(200, 46);
            this.btnAllItem.TabIndex = 0;
            this.btnAllItem.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAllItem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAllItem.TextMarginLeft = 0;
            this.btnAllItem.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAllItem.UseDefaultRadiusAndThickness = true;
            this.btnAllItem.Click += new System.EventHandler(this.btnAllItem_Click);
            // 
            // btnDashboard
            // 
            this.btnDashboard.AllowAnimations = true;
            this.btnDashboard.AllowMouseEffects = true;
            this.btnDashboard.AllowToggling = false;
            this.btnDashboard.AnimationSpeed = 200;
            this.btnDashboard.AutoGenerateColors = false;
            this.btnDashboard.AutoRoundBorders = false;
            this.btnDashboard.AutoSizeLeftIcon = true;
            this.btnDashboard.AutoSizeRightIcon = true;
            this.btnDashboard.BackColor = System.Drawing.Color.Transparent;
            this.btnDashboard.BackColor1 = System.Drawing.Color.Transparent;
            this.btnDashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDashboard.BackgroundImage")));
            this.btnDashboard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.ButtonText = "DASHBOARD";
            this.btnDashboard.ButtonTextMarginLeft = 0;
            this.btnDashboard.ColorContrastOnClick = 45;
            this.btnDashboard.ColorContrastOnHover = 45;
            this.btnDashboard.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges25.BottomLeft = true;
            borderEdges25.BottomRight = true;
            borderEdges25.TopLeft = true;
            borderEdges25.TopRight = true;
            this.btnDashboard.CustomizableEdges = borderEdges25;
            this.btnDashboard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDashboard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.btnDashboard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDashboard.Font = new System.Drawing.Font("Kode Mono", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDashboard.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnDashboard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashboard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDashboard.IconMarginLeft = 11;
            this.btnDashboard.IconPadding = 10;
            this.btnDashboard.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDashboard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDashboard.IconSize = 25;
            this.btnDashboard.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnDashboard.IdleBorderRadius = 1;
            this.btnDashboard.IdleBorderThickness = 1;
            this.btnDashboard.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnDashboard.IdleIconLeftImage = global::Restuarant_POS.Properties.Resources.dashboard_solid_24;
            this.btnDashboard.IdleIconRightImage = null;
            this.btnDashboard.IndicateFocus = false;
            this.btnDashboard.Location = new System.Drawing.Point(0, 73);
            this.btnDashboard.Name = "btnDashboard";
            this.btnDashboard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.OnDisabledState.BorderRadius = 1;
            this.btnDashboard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnDisabledState.BorderThickness = 1;
            this.btnDashboard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.OnDisabledState.IconLeftImage = null;
            this.btnDashboard.OnDisabledState.IconRightImage = null;
            this.btnDashboard.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDashboard.onHoverState.BorderRadius = 1;
            this.btnDashboard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.onHoverState.BorderThickness = 1;
            this.btnDashboard.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDashboard.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.onHoverState.IconLeftImage = null;
            this.btnDashboard.onHoverState.IconRightImage = null;
            this.btnDashboard.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnDashboard.OnIdleState.BorderRadius = 1;
            this.btnDashboard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnIdleState.BorderThickness = 1;
            this.btnDashboard.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnDashboard.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(120)))), ((int)(((byte)(40)))));
            this.btnDashboard.OnIdleState.IconLeftImage = global::Restuarant_POS.Properties.Resources.dashboard_solid_24;
            this.btnDashboard.OnIdleState.IconRightImage = null;
            this.btnDashboard.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDashboard.OnPressedState.BorderRadius = 1;
            this.btnDashboard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnPressedState.BorderThickness = 1;
            this.btnDashboard.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDashboard.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.OnPressedState.IconLeftImage = null;
            this.btnDashboard.OnPressedState.IconRightImage = null;
            this.btnDashboard.Size = new System.Drawing.Size(200, 46);
            this.btnDashboard.TabIndex = 1;
            this.btnDashboard.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDashboard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDashboard.TextMarginLeft = 0;
            this.btnDashboard.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDashboard.UseDefaultRadiusAndThickness = true;
            // 
            // btnMinimize
            // 
            this.btnMinimize.AllowAnimations = true;
            this.btnMinimize.AllowMouseEffects = true;
            this.btnMinimize.AllowToggling = false;
            this.btnMinimize.AnimationSpeed = 200;
            this.btnMinimize.AutoGenerateColors = false;
            this.btnMinimize.AutoRoundBorders = false;
            this.btnMinimize.AutoSizeLeftIcon = true;
            this.btnMinimize.AutoSizeRightIcon = true;
            this.btnMinimize.BackColor = System.Drawing.Color.Transparent;
            this.btnMinimize.BackColor1 = System.Drawing.Color.Transparent;
            this.btnMinimize.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnMinimize.BackgroundImage")));
            this.btnMinimize.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMinimize.ButtonText = "";
            this.btnMinimize.ButtonTextMarginLeft = 0;
            this.btnMinimize.ColorContrastOnClick = 45;
            this.btnMinimize.ColorContrastOnHover = 45;
            this.btnMinimize.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges26.BottomLeft = true;
            borderEdges26.BottomRight = true;
            borderEdges26.TopLeft = true;
            borderEdges26.TopRight = true;
            this.btnMinimize.CustomizableEdges = borderEdges26;
            this.btnMinimize.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnMinimize.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMinimize.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMinimize.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMinimize.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnMinimize.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnMinimize.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnMinimize.ForeColor = System.Drawing.Color.Transparent;
            this.btnMinimize.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMinimize.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnMinimize.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnMinimize.IconMarginLeft = 11;
            this.btnMinimize.IconPadding = 10;
            this.btnMinimize.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnMinimize.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnMinimize.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnMinimize.IconSize = 25;
            this.btnMinimize.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnMinimize.IdleBorderRadius = 1;
            this.btnMinimize.IdleBorderThickness = 1;
            this.btnMinimize.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnMinimize.IdleIconLeftImage = global::Restuarant_POS.Properties.Resources.arrow_from_top_regular_24;
            this.btnMinimize.IdleIconRightImage = null;
            this.btnMinimize.IndicateFocus = false;
            this.btnMinimize.Location = new System.Drawing.Point(39, 0);
            this.btnMinimize.Name = "btnMinimize";
            this.btnMinimize.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMinimize.OnDisabledState.BorderRadius = 1;
            this.btnMinimize.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMinimize.OnDisabledState.BorderThickness = 1;
            this.btnMinimize.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMinimize.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMinimize.OnDisabledState.IconLeftImage = null;
            this.btnMinimize.OnDisabledState.IconRightImage = null;
            this.btnMinimize.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnMinimize.onHoverState.BorderRadius = 1;
            this.btnMinimize.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMinimize.onHoverState.BorderThickness = 1;
            this.btnMinimize.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnMinimize.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnMinimize.onHoverState.IconLeftImage = null;
            this.btnMinimize.onHoverState.IconRightImage = null;
            this.btnMinimize.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnMinimize.OnIdleState.BorderRadius = 1;
            this.btnMinimize.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMinimize.OnIdleState.BorderThickness = 1;
            this.btnMinimize.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnMinimize.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.btnMinimize.OnIdleState.IconLeftImage = global::Restuarant_POS.Properties.Resources.arrow_from_top_regular_24;
            this.btnMinimize.OnIdleState.IconRightImage = null;
            this.btnMinimize.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnMinimize.OnPressedState.BorderRadius = 1;
            this.btnMinimize.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMinimize.OnPressedState.BorderThickness = 1;
            this.btnMinimize.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnMinimize.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnMinimize.OnPressedState.IconLeftImage = null;
            this.btnMinimize.OnPressedState.IconRightImage = null;
            this.btnMinimize.Size = new System.Drawing.Size(39, 40);
            this.btnMinimize.TabIndex = 0;
            this.btnMinimize.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnMinimize.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnMinimize.TextMarginLeft = 0;
            this.btnMinimize.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnMinimize.UseDefaultRadiusAndThickness = true;
            this.btnMinimize.Click += new System.EventHandler(this.btnMinimize_Click);
            // 
            // btnClose
            // 
            this.btnClose.AllowAnimations = true;
            this.btnClose.AllowMouseEffects = true;
            this.btnClose.AllowToggling = false;
            this.btnClose.AnimationSpeed = 200;
            this.btnClose.AutoGenerateColors = false;
            this.btnClose.AutoRoundBorders = false;
            this.btnClose.AutoSizeLeftIcon = true;
            this.btnClose.AutoSizeRightIcon = true;
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.BackColor1 = System.Drawing.Color.Transparent;
            this.btnClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClose.BackgroundImage")));
            this.btnClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.ButtonText = "";
            this.btnClose.ButtonTextMarginLeft = 0;
            this.btnClose.ColorContrastOnClick = 45;
            this.btnClose.ColorContrastOnHover = 45;
            this.btnClose.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges27.BottomLeft = true;
            borderEdges27.BottomRight = true;
            borderEdges27.TopLeft = true;
            borderEdges27.TopRight = true;
            this.btnClose.CustomizableEdges = borderEdges27;
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnClose.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnClose.ForeColor = System.Drawing.Color.Transparent;
            this.btnClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClose.IconMarginLeft = 11;
            this.btnClose.IconPadding = 10;
            this.btnClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClose.IconSize = 25;
            this.btnClose.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnClose.IdleBorderRadius = 1;
            this.btnClose.IdleBorderThickness = 1;
            this.btnClose.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnClose.IdleIconLeftImage = global::Restuarant_POS.Properties.Resources.window_close_regular_24;
            this.btnClose.IdleIconRightImage = null;
            this.btnClose.IndicateFocus = false;
            this.btnClose.Location = new System.Drawing.Point(0, 0);
            this.btnClose.Name = "btnClose";
            this.btnClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.OnDisabledState.BorderRadius = 1;
            this.btnClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnDisabledState.BorderThickness = 1;
            this.btnClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.OnDisabledState.IconLeftImage = null;
            this.btnClose.OnDisabledState.IconRightImage = null;
            this.btnClose.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClose.onHoverState.BorderRadius = 1;
            this.btnClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.onHoverState.BorderThickness = 1;
            this.btnClose.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClose.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClose.onHoverState.IconLeftImage = null;
            this.btnClose.onHoverState.IconRightImage = null;
            this.btnClose.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnClose.OnIdleState.BorderRadius = 1;
            this.btnClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnIdleState.BorderThickness = 1;
            this.btnClose.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnClose.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.btnClose.OnIdleState.IconLeftImage = global::Restuarant_POS.Properties.Resources.window_close_regular_24;
            this.btnClose.OnIdleState.IconRightImage = null;
            this.btnClose.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClose.OnPressedState.BorderRadius = 1;
            this.btnClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnPressedState.BorderThickness = 1;
            this.btnClose.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnPressedState.IconLeftImage = null;
            this.btnClose.OnPressedState.IconRightImage = null;
            this.btnClose.Size = new System.Drawing.Size(39, 40);
            this.btnClose.TabIndex = 0;
            this.btnClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClose.TextMarginLeft = 0;
            this.btnClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClose.UseDefaultRadiusAndThickness = true;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1822, 879);
            this.Controls.Add(this.panel6);
            this.Controls.Add(this.panel7);
            this.Controls.Add(this.pnData);
            this.Controls.Add(this.panel3);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "MainForm";
            this.Padding = new System.Windows.Forms.Padding(10);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "MainForm";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.panel4.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnMinimize;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClose;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAllItem;
        private System.Windows.Forms.Panel panel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDessert;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHot;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCool;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAlcohol;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFood;
        private System.Windows.Forms.Panel panel4;
        private System.Windows.Forms.Panel panel6;
        private System.Windows.Forms.Panel panel7;
        private System.Windows.Forms.Panel pnData;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDashboard;
    }
}